markdown: GFM
title: Genshin streamer's osu! skins document
description: Find all of BTMC's skins, both past and present.
plugins:
- jekyll-remote-theme
- jekyll-readme-index
remote_theme: KTibow/cayman-dark 
